### ISSUE TITLE
First character is a dot

### ISSUE THREAD

**Issue by mahemoff** [syntruth/minitest-summarize#1]
This is a very nice library for progress, but I am seeing a dot instead of a square bracket on first character. I guess that's minitest's default output, but I suppose there's some config needed to reomve it?

![selection_486](https://user-images.githubusercontent.com/55860/48821694-77838300-edae-11e8-8969-63c843c42910.png)

**Comment by syntruth** [comment]
Hmm, I am unable to reproduce that and have been using this for weeks now. :(

What OS and version of Minitest are you on?  I'll try to test when I get a chance.

```
$ rake test
Using database: test_mop3
[Passed: 252] [Failed 0] [Error: 0] [Skipped: 0]                                    

Finished in 4.620611s, 54.5382 runs/s, 66.4414 assertions/s
```

**Comment by mahemoff** [comment]
It's Ubuntu 18.04 with and seeing this with latest Minitest, 5.11.3. That's okay, it must be some config or override on my part, I'll re-open if it looks like a genuine issue. Thanks for checking.
